### ISSUE TITLE
Request: Animated Fire

### ISSUE THREAD

**Issue by SecularSteve** [mmatyas/pegasus-theme-9999999-in-1#1]
I couldn't help but notice that the Fire in 9.png is completely static (when it shouldn't be):

![9](https://user-images.githubusercontent.com/33793273/105561253-852e4d80-5d16-11eb-8109-90b8d807e428.png)

I took the liberty of at the very least re-creating the PNG of the animation for the assets folder (accurate pixel by pixel):

![fire](https://user-images.githubusercontent.com/33793273/105562341-13f09980-5d1a-11eb-8916-ad45badfd9ad.png)

Along with a freshly cleansed 9.png:

![9](https://user-images.githubusercontent.com/33793273/105562637-4a7ae400-5d1b-11eb-9a19-2a0e44b7911b.png)

Also the ZIPs for them:

[fire.zip](https://github.com/mmatyas/pegasus-theme-9999999-in-1/files/5859262/fire.zip)
[9.zip](https://github.com/mmatyas/pegasus-theme-9999999-in-1/files/5859287/9.zip)

I haven't made the script yet, because I have 0 experience with QT. If you could implement this somehow, that would be great.

**Comment by mmatyas** [comment]
Thank you! I'll see if I can add it!

**Comment by mmatyas** [comment]
Ok, the fire should be animated now! Thanks again!
